---
# Dependabot

version: 2
updates:

  # Bundler
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"

  # Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  # Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

  # Elm
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"

  # git submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  # Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  # Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"

  # Mix
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"

  # npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  # pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
